### PR TITLE
add Kashif Chaudhry from ArbiSoft

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Comment by fredsmith** [comment]
@singingwolfboy @chrisndodge here's my PR to add Kashif as a known contributor

**Comment by singingwolfboy** [comment]
Do we have an email address for Kashif?

**Comment by sarina** [comment]
@fredsmith can you please add Kashif's email address & rebase this

**Comment by fredsmith** [comment]
@sarina @singingwolfboy - should be all set to merge.

**Pull request merged**
