### PR TITLE
Upgrade libraries

### PR DESCRIPTION
**Pull request by cpennington**
@nedbat, @shaunagm, @gsong: I'm doing some pruning in the repo.

### CODE REVIEW

**Comment by nedbat** [comment]
There seems to be four different things going on here.  Are we sure we don't want webhookdb any more?

**Comment by cpennington** [comment]
Yeah, I can split the code up. https://github.com/singingwolfboy/webhookdb should replace the in-repo webhookdb script, I think.

**Comment by gsong** [comment]
👍 from me.

**Comment by nedbat** [comment]
I don't understand what happened here.  webhookdb.py is imported by five different scripts in this repo.  https://github.com/singingwolfboy/webhookdb is the server that writes to the database that this webhookdb.py reads from.  Have I misunderstood something?

**Comment by cpennington** [comment]
Shoot. I know that I rebased that commit out. Maybe I forgot to push after that? I'll fix it to bring webhookdb.py back.

**Pull request merged**
