### PR TITLE
Add names for clarice users

### PR DESCRIPTION
**Pull request by sarina**
@aleffert do you know the names of the Clarice contributors & can you help me out w/ them here?

### CODE REVIEW

**Comment by sarina** [comment]
also who is `abhra-clarice`? Name and email address, please.

**Comment by aleffert** [comment]
@sarina

Better information is below. Do you want me to update the PR with it?

```
rohan-dhamal-clarice:
     name: Rohan Dhamal
     agreement: institution
     institution: Clarice
     email: rohan.dhamal@claricetechnologies.com
shahidtamboli:
     name: Shahid Tamboli
     agreement: institution
     institution: Clarice
     email: shahid.tamboli@claricetechnologies.com
rahul-clarice:
     name: Rahul Varma
     agreement: institution
     institution: Clarice
     email: rahul.varma@claricetechnologies.com
jotiram:
     name: Jotiram Bhagat
     agreement: institution
     institution: Clarice
     email: jotiram.bhagat@claricetechnologies.com
abhra-clarice:
     name: Abhradeep Mazumder
     agreement: institution
     institution: Clarice
     email: abhradeep.mazumder@claricetechnologies.com
```

**Comment by sarina** [comment]
@aleffert that would be great. And as there are new contractors, if you could add them to this list, we'd really appreciate it. We have a lot of scripts that do reporting, and that "institution: Clarice" line keeps the bot from commenting on PRs and our tools from reporting their work as open source work.

**Comment by aleffert** [comment]
@sarina updated. I'll do my best to keep it updated. I think there might be one or two not on here that I'll try to track down.

**Comment by sarina** [comment]
Sure thing! The only person showing up in my reporting this week is abhra-clarice. I'll ping you if I see any others in the future. thanks a ton

**Pull request merged**
